### ISSUE TITLE
Permissions system

### ISSUE THREAD

**Issue by ducc** [ducc/dabGateway#1]
- [x] Database
  table server_permissions: server_id text, role_id text, bits int
- [x] Endpoints
  GET `/permissions/:server` list roles & permission nodes
  POST `/permissions/:server` create new role & permissions
  DELETE `/permissions/:server` delete server permissions
  GET `/permissions/:server/:role` show role permission nodes
  PUT `/permissions/:server/:role` update permissions
  DELETE `/permissions/:server/:role` delete role permissions

**Comment by sponges** [comment]
Removed in favor of simple feature

**Comment by sponges** [comment]
Simple system was shit in comparison to this

**Comment by sponges** [comment]
Reimplementing https://github.com/sponges/dabGateway/commit/254d445926d697394cefd2a68e1ec05db571b8ce

**Comment by ducc** [comment]
lol i forgot i hadnt done the method bodies

**Comment by ducc** [comment]
hopefully the last time i close this..
